# -*- coding: utf-8 -*-
import re
dic = {re.compile("^a$"):["ꀊ", "ꀋp","ꀈt","ꀉx"],
                  re.compile("^ap$"):["ꀋ"],
                  re.compile("^at$"):["ꀈ"],
                  re.compile("^ax$"):["ꀉ"],                  
                  re.compile("^i$"): ["ꀂ", "ꀃp", "ꀀt", "ꀁx", "ꀆe", "ꀇep", "ꀄet", "ꀅex"],
                  re.compile("^ip$"):["ꀃ"],
                  re.compile("^it$"):["ꀀ"],
                  re.compile("^ix$"):["ꀁ"],
                  re.compile("^ie$"):["ꀆ", "ꀇp", "ꀄt", "ꀅx"],
                  re.compile("^iep"):["ꀇ"],
                  re.compile("^iet"):["ꀄ"],
                  re.compile("^iex"):["ꀅ"],
                  #wikipediaにuの最初の文字はない(2020/4/28時点)
                  re.compile("^u$"):["ꇨ","ꀍo","ꀎop","ꀌox"],
                  re.compile("^uo$"):["ꀍ","ꀎp","ꀌx"],
                  re.compile("^uop$"):["ꀎ"],
                  re.compile("^uox$"):["ꀌ"],
                  re.compile("^e$"):["ꀔ", "ꀓx"],
                  re.compile("^ex$"):["ꀓ"],
                  re.compile("^o$"):["ꀑ", "ꀒp", "ꀏt", "ꀐx"],
                  re.compile("^op$"):["ꀒ"],
                  re.compile("^ot$"):["ꀏ"],
                  re.compile("^ox$"):["ꀐ"],
                  re.compile("^y$"):["ꑳ","ꑳ","ꑴ","ꑱ","ꑲ","ꑷ","ꑸ","ꑵ","ꑶ","ꑻ","ꑼ","ꑹ","ꑺ"],
                  re.compile("^yi$"):["ꑳ", "ꑴ", "ꑱ", "ꑲ", "ꑷ", "ꑸ", "ꑵ", "ꑶ"],
                  re.compile("^yie$"):["ꑷ", "ꑸ", "ꑵ", "ꑶ"],
                  re.compile("^yiep$"):["ꑸ"],
                  re.compile("^yiet$"):["ꑵ"],
                  re.compile("^yiex$"):["ꑶ"],
                  re.compile("^b$"):["ꀠa", "ꀡap", "ꀞat", "ꀟax",
                            "ꀘi", "ꀙip", "ꀖit", "ꀗix",
                            "ꀜie","ꀝiep","ꀚiet","ꀛiex",
                            "ꀪe", "ꀫep", "ꀩex"
                            "ꀮu", "ꀯup", "ꀬut", "ꀭux", "ꀱur", "ꀰux", "꒥ub",
                            "ꀣuo", "ꀤuop", "ꀢuox", 
                            "ꀴy", "ꀵyp", "ꀲyt", "ꀳyx", "ꀷyr", "ꀶyrx",
                            "ꀧo","ꀨop","ꀥot","ꀦox"],
                            
                  re.compile("^ba$"):["ꀠ", "ꀡp", "ꀞt", "ꀟx"],
                  re.compile("^bap$"):["ꀡ"],
                  re.compile("^bat$"):["ꀞ"],
                  re.compile("^bax$"):["ꀟ"],
                  
                  re.compile("^bi$"):["ꀘ", "ꀙp", "ꀖt", "ꀗx", "ꀜe", "ꀝep", "ꀚet", "ꀛex"],
                  re.compile("^bip$"):["ꀙ"],
                  re.compile("^bit$"):["ꀖ"],
                  re.compile("^bix$"):["ꀗ"],
                  re.compile("^bie$"):["ꀜ", "ꀝp", "ꀚt", "ꀛx"],
                  re.compile("^biep$"):["ꀝ"],
                  re.compile("^biet$"):["ꀚ"],
                  re.compile("^biex$"):["ꀛ"],   
                  
                  re.compile("^be$"):["ꀪ", "ꀫp", "ꀩx"],
                  re.compile("^bep$"):["ꀫ"],
                  re.compile("^bex$"):["ꀩ"],
                  
                  re.compile("^bu$"):["ꀮ", "ꀯp", "ꀬt", "ꀭx", "ꀣo", "ꀤop", "ꀢox", "ꀱr", "ꀰx", "꒥b"],                  
                  re.compile("^bup$"):["ꀯ"],
                  re.compile("^but$"):["ꀬ"],
                  re.compile("^bux$"):["ꀭ"],
                  re.compile("^buo$"):["ꀣ", "ꀤp", "ꀢx"],
                  re.compile("^buop$"):["ꀤ"],
                  re.compile("^buox$"):["ꀢ"],
                  re.compile("^bur$"):["ꀱ"],
                  re.compile("^bux$"):["ꀰ"],
                  re.compile("^bub$"):["꒥"],                            
                  
                  re.compile("^bo$"):["ꀧ","ꀨp","ꀥt","ꀦx"],
                  re.compile("^bop$"):["ꀨ"],
                  re.compile("^bot$"):["ꀥ"],
                  re.compile("^box$"):["ꀦ"],
                  
                  re.compile("^by$"):["ꀴ", "ꀵp", "ꀲt", "ꀳx", "ꀷr", "ꀶrx"],
                  re.compile("^byp$"):["ꀵ"],
                  re.compile("^byt$"):["ꀲ"],
                  re.compile("^byx$"):["ꀳ"],
                  re.compile("^byr$"):["ꀷ", "ꀶx"],
                  re.compile("^byrx$"):["ꀶ"],
                  re.compile("^p$"):["ꁁa", "ꁂap", "ꀿat", "ꁀax",
                            "ꀺi","ꀻip","ꀸit","ꀹix",
                            "ꀽie","ꀾiep","ꀼiex",
                            "ꁌu", "ꁍup", "ꁊut", "ꁋux", "ꁏur", "ꁎurx",
                            "ꁄuo", "ꁅuop", "ꁃuox",
                            "ꁒy", "ꁓyp", "ꁐyt", "ꁑyx", "ꁕyr", "ꁔyrx"],
                  re.compile("^pa$"):["ꁁ", "ꁂp", "ꀿt", "ꁀx"],
                  re.compile("^pap$"):["ꁂ"],
                  re.compile("^pat$"):["ꀿ"],
                  re.compile("^pax$"):["ꁀ"],
                  
                  re.compile("^pi$"):["ꀺ","ꀻp","ꀸt","ꀹx","ꀽe","ꀾep","ꀼex"],
                  re.compile("^pip$"):["ꀻ"],
                  re.compile("^pit$"):["ꀸ"],
                  re.compile("^pix$"):["ꀹ"],
                  
                  re.compile("^pie$"):["ꀽ","ꀾp","ꀼx"],
                  re.compile("^piep$"):["ꀾ"],
                  re.compile("^piex$"):["ꀼ"],
                  
                  re.compile("^pu$"):["ꁌ", "ꁍp", "ꁊt", "ꁋx", "ꁏr", "ꁎrx", "ꁄo", "ꁅop", "ꁃox"],
                  re.compile("^pup$"):["ꁍ"],
                  re.compile("^put$"):["ꁊ"],
                  re.compile("^pux$"):["ꁋ"],
                  re.compile("^pur$"):["ꁏ", "ꁎx"],
                  re.compile("^purx$"):["ꁎ"],
                  
                  re.compile("^puo$"):["ꁄ", "ꁅp", "ꁃx"],
                  re.compile("^puop$"):["ꁅ"],
                  re.compile("^puox$"):["ꁃ"],
                  
                  re.compile("^py$"):["ꁒ", "ꁓp", "ꁐt", "ꁑx", "ꁕr", "ꁔrx"],
                  re.compile("^pyp$"):["ꁓ"],
                  re.compile("^pyt$"):["ꁐ"],
                  re.compile("^pyx$"):["ꁑ"],
                  re.compile("^pyr$"):["ꁕ", "ꁔx"],
                  re.compile("^pyrx$"):["ꁔ"],
                  
                  re.compile("^bb$"):["ꁠa", "ꁡap", "ꁞat", "ꁟax",
                            "ꁘi", "ꁙip", "ꁖit", "ꁗix",
                            "ꁜie", "ꁝiep", "ꁚiet", "ꁛiex",
                            "ꁮu","ꁯup","ꁬut","ꁭux", "ꁱur","ꁰurx"
                            "ꁣuo","ꁤuop","ꁢuox",
                            "ꁴy","ꁵyp","ꁲyt","ꁳyx",
                            "ꁧo", "ꁨop", "ꁥot", "ꁦox"],
                            
                  re.compile("^bba$"):["ꁠ", "ꁡp", "ꁞt", "ꁟx"],
                  re.compile("^bbap$"):["ꁡ"],
                  re.compile("^bbat$"):["ꁞ"],
                  re.compile("^bbax$"):["ꁟ"],
                  
                  re.compile("^bbi$"):["ꁘ","ꁙp","ꁖt","ꁗx","ꁜe" "ꁝep" "ꁚet" "ꁛex"],
                  re.compile("^bbip$"):["ꁙ"],
                  re.compile("^bbit$"):["ꁖ"],
                  re.compile("^bbix$"):["ꁗ"],
                  re.compile("^bbie$"):["ꁜ","ꁝp","ꁚt","ꁛx"],
                  re.compile("^bbiep$"):["ꁝ"],
                  re.compile("^bbiet$"):["ꁚ"],
                  re.compile("^bbiex$"):["ꁛ"],
                  
                  re.compile("^bbu$"):["ꁮ","ꁯp","ꁬt","ꁭx","ꁱr","ꁰrx","ꁣo","ꁤop","ꁢox"],
                  re.compile("^bbup$"):["ꁯ"],
                  re.compile("^bbut$"):["ꁬ"],
                  re.compile("^bbux$"):["ꁭ"],
                  re.compile("^bbur$"):["ꁱ"],
                  re.compile("^bburx$"):["ꁰ"],
                  
                  re.compile("^bbuo$"):["ꁣ","ꁤp","ꁢx"],
                  re.compile("^bbuop$"):["ꁤ"],
                  re.compile("^bbuox$"):["ꁢ"],
                  
                  re.compile("^bbo$"):["ꁧ", "ꁨp", "ꁥt", "ꁦx"],
                  re.compile("^bbop$"):["ꁨ"],
                  re.compile("^bbot$"):["ꁥ"],
                  re.compile("^bbop$"):["ꁦ"],
                  
                  re.compile("^bbe$"):["ꁪ","ꁫp","ꁩx"],
                  re.compile("^bbep$"):["ꁫ"],
                  re.compile("^bbepx$"):["ꁩ"],
                  
                  re.compile("^bby$"):["ꁴ","ꁵp","ꁲt","ꁳx"],
                  re.compile("^bbyp$"):["ꁵ"],
                  re.compile("^bbyt$"):["ꁲ"],
                  re.compile("^bbyx$"):["ꁳ"],
                  
                  re.compile("^nb$"):["ꁿa", "ꂀap", "ꁽat", "ꁾax",
                            "ꁸi","ꁹip","ꁶit","ꁷix", "ꁻie","ꁼiep","ꁺiex",
                            "ꁻie","ꁼiep","ꁺiex",
                            "ꂇu","ꂈup","ꂅut","ꂆux","ꂊur","ꂉurx",
                            "ꂃo","ꂄop","ꂁot","ꂂox",
                            "ꂍy","ꂎyp","ꂋyt","ꂌyx","ꂐyr","ꂏyrx"],
                  re.compile("^nba$"):["ꁿ", "ꂀp", "ꁽt", "ꁾx"],
                  re.compile("^nbap$"):["ꂀ"],
                  re.compile("^nbat$"):["ꁽ"],
                  re.compile("^nbax$"):["ꁾ"],
                  
                  re.compile("^nbi$"):["ꁸ","ꁹp","ꁶt","ꁷx", "ꁻe","ꁼep","ꁺex"],
                  re.compile("^nbip$"):["ꁹ"],
                  re.compile("^nbit$"):["ꁶ"],
                  re.compile("^nbix$"):["ꁷ"],
                  
                  re.compile("^nbie$"):["ꁻ","ꁼp","ꁺx"],
                  re.compile("^nbiep$"):["ꁼ"],
                  re.compile("^nbiex$"):["ꁺ"],
                  
                  re.compile("^nbu$"):["ꂇ","ꂈp","ꂅt","ꂆx","ꂊr","ꂉrx"],
                  re.compile("^nbup$"):["ꂈ"],
                  re.compile("^nbut$"):["ꂅ"],
                  re.compile("^nbux$"):["ꂆ"],
                  re.compile("^nbur$"):["ꂊ", "ꂉx"],
                  re.compile("^nburx$"):["ꂉ"],
                  
                  re.compile("^nby$"):["ꂍ","ꂎp","ꂋt","ꂌx","ꂐr","ꂏrx"],
                  re.compile("^nbyp$"):["ꂎ"],
                  re.compile("^nbyt$"):["ꂋ"],
                  re.compile("^nbyx$"):["ꂌ"],
                  re.compile("^nbyr$"):["ꂐ", "ꂏx"],
                  re.compile("^nbyrx$"):["ꂏ"],
                  
                  re.compile("^nbo$"):["ꂃ","ꂄp","ꂁt","ꂂx"],
                  re.compile("^nbop$"):["ꂄ"],
                  re.compile("^nbot$"):["ꂁ"],
                  re.compile("^nbox$"):["ꂂ"],
                  
                  re.compile("^hma$"):["ꂚ","ꂛp","ꂘt","ꂙx"],
                  re.compile("^hmap$"):["ꂛ"],
                  
                  re.compile("^hmi$"):["ꂓ","ꂔp","ꂑt","ꂒx","ꂖe","ꂗep","ꂕex"],
                  re.compile("^hmip$"):["ꂔ"],
                  re.compile("^hmit$"):["ꂑ"],
                  re.compile("^hmix$"):["ꂒ"],                  
                  
                  re.compile("^hmie$"):["ꂖ","ꂗp","ꂕx"],
                  re.compile("^hmiep$"):["ꂗ"],
                  re.compile("^hmiex$"):["ꂕ"],
                  
                  re.compile("^hmu$"):["ꂥ","ꂦp","ꂣt","ꂤx","ꂨr","ꂧrx"],
                  re.compile("^hmup$"):["ꂦ"],
                  re.compile("^hmut$"):["ꂣ"],
                  re.compile("^hmux$"):["ꂣ"],
                  
                  re.compile("^hmuo$"):["ꂝ","ꂞp","ꂜx"],
                  re.compile("^hmuop$"):["ꂞ"],
                  re.compile("^hmuox$"):["ꂜ"],
                  
                  re.compile("^hmy$"):["ꂪ","ꂫp","ꂩx","ꂭr","ꂬrx"],
                  re.compile("^hmyp$"):["ꂫ"],
                  re.compile("^hmyx$"):["ꂩ"],
                  re.compile("^hmyr$"):["ꂭ", "ꂬrx"],
                  re.compile("^hmyrx$"):["ꂬ"],
                  
                  re.compile("^m$"):
                           ["ꂷa", "ꂸap", "ꂵat", "ꂶax",
                            "ꂰi", "ꂱip", "ꂮit", "ꂯix", "ꂳie", "ꂴiep", "ꂲiex",
                            "ꃅu", "ꃆup", "ꃃut", "ꃄux", "ꂻuo", "ꂼuop", "ꂹuot", "ꂺuox",
                            "ꃂe", "ꃁex",
                            "ꂿo", "ꃀop", "ꂽot", "ꂾox",
                            "ꃋy", "ꃌyp", "ꃉyt", "ꃊyx"],
                            
                  re.compile("^ma$"):["ꂷ", "ꂸ", "ꂵ", "ꂶ"],
                  re.compile("^map$"):["ꂸ"],
                  re.compile("^mat$"):["ꂵ"],
                  re.compile("^max$"):["ꂶ"],
                  
                  re.compile("^mi$"):["ꂰ", "ꂱp", "ꂮt", "ꂯx", "ꂳe", "ꂴep", "ꂲex"],
                  re.compile("^mip$"):["ꂱ"],
                  re.compile("^mit$"):["ꂮ"],
                  re.compile("^mix$"):["ꂯ"],
                  
                  re.compile("^mie$"):["ꂳ", "ꂴ", "ꂲ"],
                  re.compile("^miep$"):["ꂴ"],
                  re.compile("^miex$"):["ꂲ"],
                  
                  re.compile("^mu$"):["ꃅ", "ꃆp", "ꃃt", "ꃄx", "ꂻo", "ꂼop", "ꂹot", "ꂺox"],
                  re.compile("^mup$"):["ꃆ"],
                  re.compile("^mut$"):["ꃃ"],
                  re.compile("^mux$"):["ꃄ"],
                  
                  re.compile("^muo$"):["ꂻ", "ꂼp", "ꂹt", "ꂺx"],
                  re.compile("^muop$"):["ꂼ"],
                  re.compile("^muot$"):["ꂹ"],
                  re.compile("^muox$"):["ꂺ"],
                  
                  re.compile("^me$"):["ꃂ", "ꃁx"],
                  re.compile("^mex$"):["ꃁ"],                  
                  
                  re.compile("^mo$"):["ꂿ", "ꃀp", "ꂽt", "ꂾx"],
                  re.compile("^mop$"):["ꃀ"],
                  re.compile("^mot$"):["ꂽ"],
                  re.compile("^mox$"):["ꂾ"],
                  
                  re.compile("^my$"):["ꃋ", "ꃌp", "ꃉt", "ꃊx"],
                  re.compile("^myp$"):["ꃌ"],
                  re.compile("^myt$"):["ꃉ"],
                  re.compile("^myx$"):["ꃊ"],
                  re.compile("^f$"):["ꃓa", "ꃔap", "ꃑat", "ꃒax",
                            "ꃏi", "ꃐip", "ꃍit", "ꃎix",
                            "ꃚu", "ꃛup", "ꃘut", "ꃙux",
                            "ꃖo", "ꃗop", "ꃕox",
                            "ꃠy", "ꃡyp", "ꃞyt", "ꃟyx"],
                            
                  
                  re.compile("^fa$"):["ꃓ", "ꃔp", "ꃑt", "ꃒx"],
                  re.compile("^fap$"):["ꃔ"],
                  re.compile("^fat$"):["ꃑ"],
                  re.compile("^fax$"):["ꃒ"],
                  
                  re.compile("^fi$"):["ꃏ", "ꃐp", "ꃍt", "ꃎx"],
                  re.compile("^fip$"):["ꃐ"],
                  re.compile("^fit$"):["ꃍ"],
                  re.compile("^fix$"):["ꃎ"],
                  
                  re.compile("^fu$"):["ꃚ", "ꃛp", "ꃘt", "ꃙx"],
                  re.compile("^fup$"):["ꃛ"],
                  re.compile("^fut$"):["ꃘ"],
                  re.compile("^fux$"):["ꃎ"],
                  
                  re.compile("^fo$"):["ꃖ", "ꃗp", "ꃕx"],
                  re.compile("^fop$"):["ꃗ"],
                  re.compile("^fox$"):["ꃕ"],
                  
               
                  re.compile("^fy$"):["ꃠ", "ꃡp", "ꃞt", "ꃟx"],
                  re.compile("^fyp$"):["ꃡ"],
                  re.compile("^fyt$"):["ꃞ"],
                  re.compile("^fyx$"):["ꃟ"],
                  re.compile("^v$"):["ꃬa", "ꃭap", "ꃪat", "ꃫax",
                            "ꃤi", "ꃥip", "ꃢit", "ꃣix", "ꃨie", "ꃩiep", "ꃦiet", "ꃧiex",
                            "ꃶu", "ꃷup", "ꃴut", "ꃵux", "ꃹur", "ꃸurx",
                            "ꃳe", "ꃳep", "ꃲex",
                            "ꃰo", "ꃱop", "ꃮot", "ꃯox",
                            "ꃼy", "ꃽyp", "ꃺyt", "ꃻyx", "ꃿyr", "ꃾyrx"],
                  re.compile("^va$"):["ꃬ", "ꃭp", "ꃪt", "ꃫx"],
                  re.compile("^vap$"):["ꃭ"],
                  re.compile("^vat$"):["ꃪ"],
                  re.compile("^vax$"):["ꃫ"],
                  
                  re.compile("^vi$"):["ꃤ", "ꃥp", "ꃢt", "ꃣx", "ꃨ", "ꃩp", "ꃦt", "ꃧx"],
                  re.compile("^vip$"):["ꃥ"],
                  re.compile("^vit$"):["ꃢ"],
                  re.compile("^vix$"):["ꃣ"],
                  
                  re.compile("^vie$"):["ꃨ"],
                  re.compile("^viep$"):["ꃩ"],
                  re.compile("^viet$"):["ꃦ"],
                  re.compile("^viex$"):["ꃧ"],
                  
                  re.compile("^vu$"):["ꃶ", "ꃷp", "ꃴt", "ꃵx", "ꃹr", "ꃸrx"],
                  re.compile("^vup$"):["ꃷ"],
                  re.compile("^vut$"):["ꃴ"],
                  re.compile("^vux$"):["ꃵ"],
                  re.compile("^vur$"):["ꃹ", "ꃸx"],
                  re.compile("^vurx$"):["ꃸ"],
                  
                  re.compile("^ve$"):["ꃳp", "ꃲx"],
                  re.compile("^vep$"):["ꃳ"],      
                  re.compile("^vex$"):["ꃲ"], 
                  
                  re.compile("^vo$"):["ꃰ", "ꃱp", "ꃮt", "ꃯx"],
                  re.compile("^vop$"):["ꃱ"],
                  re.compile("^vot$"):["ꃮ"],
                  re.compile("^vox$"):["ꃯ"],
                  
                  re.compile("^vy$"):["ꃼ", "ꃽp", "ꃺt", "ꃻx", "ꃿr", "ꃾrx"],
                  re.compile("^vyp$"):["ꃽ"],
                  re.compile("^vyt$"):["ꃺ"],
                  re.compile("^vyx$"):["ꃻ"],
                  re.compile("^vyr$"):["ꃿ", "ꃾx"],
                  re.compile("^vyrx$"):["ꃾ"],
                  re.compile("^d$"):["ꄉa", "ꄊap", "ꄇat", "ꄈax",
                            "ꄂi", "ꄃip", "ꄀit", "ꄁix", "ꄅie", "ꄆiep", "ꄄiex",
                            "ꄖu", "ꄗup", "ꄔut", "ꄕux", "ꄙur", "ꄘurx", "ꄌuo", "ꄋuox",
                            "ꄒe", "ꄓep", "ꄑex",
                            "ꄏo", "ꄐop", "ꄍot", "ꄎox"],
                  re.compile("^da$"):["ꄉ", "ꄊp", "ꄇt", "ꄈx"],
                  re.compile("^dap$"):["ꄊ"],
                  re.compile("^dat$"):["ꄇ"],
                  re.compile("^dax$"):["ꄈ"],
                  
                  re.compile("^di$"):["ꄂ", "ꄃp", "ꄀt", "ꄁx", "ꄅe", "ꄆep", "ꄄex"],
                  re.compile("^dip$"):["ꄊ"],
                  re.compile("^dit$"):["ꄇ"],
                  re.compile("^dix$"):["ꄈ"],
                  
                  re.compile("^die$"):["ꄅ","ꄆp","ꄄx"],
                  re.compile("^diep$"):["ꄆ"],
                  re.compile("^diex$"):["ꄄ"],
                  
                  re.compile("^du$"):["ꄖ", "ꄗp", "ꄔt", "ꄕx", "ꄙr", "ꄘrx", "ꄌo", "ꄋox"],                  
                  re.compile("^dup$"):["ꄗ"],
                  re.compile("^dut$"):["ꄔ"],
                  re.compile("^dux$"):["ꄕ"],
                  re.compile("^dur$"):["ꄙ", "ꄘx"],
                  re.compile("^durx$"):["ꄘ"],
                  re.compile("^duo$"):["ꄌ", "ꄋx"],
                  re.compile("^duox$"):["ꄋ"],
                  
                  re.compile("^de$"):["ꄒ", "ꄓp", "ꄑx"],
                  re.compile("^dep$"):["ꄓ"],
                  re.compile("^dex$"):["ꄑ"],
                  
                  re.compile("^do$"):["ꄏ", "ꄐp", "ꄍt", "ꄎx"],
                  re.compile("^dop$"):["ꄐ"],
                  re.compile("^dot$"):["ꄍ"],
                  re.compile("^dox$"):["ꄎ"],
                  
                  re.compile("^t$"):["ꄣa", "ꄤap", "ꄡat", "ꄢax",
                            "ꄜi", "ꄝip", "ꄚit", "ꄛix", "ꄟie", "ꄠiep", "ꄞiex",
                            "ꄲu", "ꄳup", "ꄰut", "ꄱux", "ꄧuo", "ꄨuop", "ꄥuot", "ꄦuox",
                            "ꄮe", "ꄯep", "ꄭex",
                            "ꄫo", "ꄬop", "ꄩot", "ꄪox"],
                  re.compile("^ta$"):["ꄣ", "ꄤp", "ꄡt", "ꄢx"],
                  re.compile("^tap$"):["ꄤ"],
                  re.compile("^tat$"):["ꄡ"],
                  re.compile("^tax$"):["ꄢ"],
                  
                  re.compile("^ti$"):["ꄜ", "ꄝp", "ꄚt", "ꄛx", "ꄟ", "ꄠep", "ꄞex"],
                  re.compile("^tip$"):["ꄝp"],
                  re.compile("^tit$"):["ꄚt"],
                  re.compile("^tix$"):["ꄛx"],
                  re.compile("^tie$"):["ꄟ"],
                  re.compile("^tiep$"):["ꄠ"],
                  re.compile("^tiex$"):["ꄞ"],
                  
                  re.compile("^tu$"):["ꄲ", "ꄳp", "ꄰt", "ꄱx", "ꄧo", "ꄨop", "ꄥot", "ꄦox"],
                  re.compile("^tup$"):["ꄳp"],
                  re.compile("^tut$"):["ꄰt"],
                  re.compile("^tux$"):["ꄱx"],
                  re.compile("^tuo$"):["ꄧ", "ꄨp", "ꄥt", "ꄦx"],
                  re.compile("^tuop$"):["ꄨ"],
                  re.compile("^tuot$"):["ꄥ"],
                  re.compile("^tuox$"):["ꄦ"],
                  
                  re.compile("^te$"):["ꄮ", "ꄯp", "ꄭx"],
                  re.compile("^tep$"):["ꄯ"],
                  re.compile("^tex$"):["ꄭ"],
                  
                  re.compile("^to$"):["ꄫ", "ꄬp", "ꄩt", "ꄪx"],
                  re.compile("^top$"):["ꄬp"],
                  re.compile("^tot$"):["ꄩt"],
                  re.compile("^tox$"):["ꄪx"],
                  
                  re.compile("^dd$"):["ꄿa", "ꅀap", "ꄽat", "ꄾax",
                            "ꄸi", "ꄹip", "ꄶit", "ꄷix", "ꄻie", "ꄼiep", "ꄺiex",
                            "ꅍu", "ꅎup", "ꅋut", "ꅌux", "ꅂuo", "ꅃuop", "ꅁuox",
                            "ꅉe", "ꅊep", "ꅈex"],
                  re.compile("^dda$"):["ꄿ", "ꅀp", "ꄽt", "ꄾx"],
                  re.compile("^ddap$"):["ꅀ"],
                  re.compile("^ddat$"):["ꄽ"],
                  re.compile("^ddax$"):["ꄾ"],
                  
                  re.compile("^ddi$"):["ꄸ", "ꄹp", "ꄶt", "ꄷx", "ꄻe", "ꄼep", "ꄺex"],
                  re.compile("^ddip$"):["ꄹ"],
                  re.compile("^ddit$"):["ꄶ"],
                  re.compile("^ddix$"):["ꄷ"],
                  re.compile("^ddie$"):["ꄻ"],
                  re.compile("^ddiep$"):["ꄼ"],
                  re.compile("^ddiex$"):["ꄺ"],
                  
                  re.compile("^ddu$"):["ꅍ", "ꅎp", "ꅋt", "ꅌx", "ꅐr", "ꅏrx","ꅂo", "ꅃop", "ꅁox"],
                  re.compile("^ddup$"):["ꅎ"],
                  re.compile("^ddut$"):["ꅋ"],
                  re.compile("^ddux$"):["ꅌ"],
                  re.compile("^ddur$"):["ꅐ"],
                  re.compile("^ddurx$"):["ꅏ"],
                  re.compile("^dduo$"):["ꅂ"],
                  re.compile("^dduop$"):["ꅃ"],
                  re.compile("^dduox$"):["ꅁ"],
                  
                  re.compile("^dde$"):["ꅉ", "ꅊp", "ꅈx"],
                  re.compile("^ddep$"):["ꅊ"],
                  re.compile("^ddex$"):["ꅈ"],
                  
                  re.compile("^nd$"):["ꅙ", "ꅚp", "ꅗt", "ꅘx",
                            "ꅓi", "ꅔip", "ꅑit", "ꅒix", "ꅖie", "ꅕiex",
                            "ꅤu", "ꅥup", "ꅢut", "ꅣux", "ꅧur", "ꅦurx",
                            "ꅝo", "ꅞop", "ꅛot", "ꅜox"],
                  
                  re.compile("^nda$"):["ꅙ", "ꅚp", "ꅗt", "ꅘx"],
                  re.compile("^ndap$"):["ꅚ"],
                  re.compile("^ndat$"):["ꅗ"],
                  re.compile("^ndax$"):["ꅘ"],
                  
                  re.compile("^ndi$"):["ꅓ", "ꅔp", "ꅑt", "ꅒx", "ꅖe", "ꅕex"],
                  re.compile("^ndip$"):["ꅔ"],
                  re.compile("^ndit$"):["ꅑ"],
                  re.compile("^ndix$"):["ꅒ"],
                  re.compile("^ndie$"):["ꅖ", "ꅕx"],
                  re.compile("^ndiex$"):["ꅕ"],
                  
                  re.compile("^ndu$"):["ꅤ", "ꅥp", "ꅢt", "ꅣx", "ꅧr", "ꅦrx"],
                  re.compile("^ndup$"):["ꅥ"],
                  re.compile("^ndut$"):["ꅢ"],
                  re.compile("^ndux$"):["ꅣ"],
                  re.compile("^ndur$"):["ꅧ", "ꅦx"],
                  re.compile("^ndurx$"):["ꅦ"],
                  
                  re.compile("^ndo$"):["ꅝ", "ꅞp", "ꅛt", "ꅜx"],
                  re.compile("^ndop$"):["ꅞ"],
                  re.compile("^ndot$"):["ꅛ"],
                  re.compile("^ndox$"):["ꅜ"],
                  re.compile("^hn$"):["ꅲ", "ꅳp", "ꅰt", "ꅱx",
                            "ꅪi", "ꅫip", "ꅨit", "ꅩix", "ꅮie", "ꅯiep", "ꅬiet", "ꅭiex",
                            "ꅼut", "ꅵuo", "ꅴux",
                            "ꅸop", "ꅶot", "ꅷox",
                            "ꅺe", "ꅻep", "ꅹex"],
                  re.compile("^hna$"):["ꅲ", "ꅳp", "ꅰt", "ꅱx"],
                  re.compile("^hnap$"):["ꅳ"],
                  re.compile("^hnat$"):["ꅰ"],
                  re.compile("^hnax$"):["ꅱ"],
                  
                  re.compile("^hni$"):["ꅪ", "ꅫp", "ꅨt", "ꅩx", "ꅮe", "ꅯep", "ꅬet", "ꅭex"],
                  re.compile("^hnip$"):["ꅫ"],
                  re.compile("^hnit$"):["ꅨ"],
                  re.compile("^hnix$"):["ꅩ"],
                  re.compile("^hnie$"):["ꅫ"],
                  re.compile("^hniep$"):["ꅯ"],
                  re.compile("^hniet$"):["ꅬ"],
                  re.compile("^hniex$"):["ꅭ"],
                  
                  re.compile("^hnu$"):["ꅼt", "ꅵo", "ꅴx"],
                  re.compile("^hnuo$"):["ꅵ"],
                  re.compile("^hnux$"):["ꅴ"],
                  
                  re.compile("^hno$"):["ꅸp", "ꅶt", "ꅷx"],
                  re.compile("^hnop$"):["ꅸ"],
                  re.compile("^hnot$"):["ꅶ"],
                  re.compile("^hnox$"):["ꅷ"],
                  
                  re.compile("^hne$"):["ꅺ", "ꅻp", "ꅹx"],
                  re.compile("^hnep$"):["ꅻ"],
                  re.compile("^hnex$"):["ꅹ"],
                  re.compile("^n$"):["ꆅa", "ꆆap", "ꆄax",
                            "ꅿi", "ꆀip", "ꅽit", "ꅾix", "ꆂie", "ꆃiep", "ꆁiex",
                            "ꆓ", "ꆔp", "ꆑt", "ꆒx", "ꆈo", "ꆉop", "ꆇox"],
                  re.compile("^na$"):["ꆅ", "ꆆp", "ꆄx"],
                  re.compile("^nap$"):["ꆆ"],
                  re.compile("^nax$"):["ꆄ"],
                  
                  re.compile("^ni$"):["ꅿ", "ꆀp", "ꅽt", "ꅾx", "ꆂe", "ꆃep", "ꆁex"],
                  re.compile("^nip$"):["ꆀ"],
                  re.compile("^nit$"):["ꅽ"],
                  re.compile("^nix$"):["ꅾ"],                  
                  re.compile("^niep$"):["ꆃ"],
                  re.compile("^niex$"):["ꆁ"],
                  
                  re.compile("^nu$"):["ꆓ", "ꆔp", "ꆑt", "ꆒx", "ꆈo", "ꆉop", "ꆇox"],
                  re.compile("^nup$"):["ꆆ"],
                  re.compile("^nux$"):["ꆄ"],
                  re.compile("^nuo$"):["ꆈ"],
                  re.compile("^nuop$"):["ꆉ"],
                  re.compile("^nuox$"):["ꆇ"],
                  
                  re.compile("^hl$"):["ꆠa","ꆡap","ꆞat","ꆟax",
                            "ꆙi","ꆚip","ꆗit","ꆘix", "ꆜie", "ꆝiep", "ꆛiex",
                            "ꆭu","ꆮup","ꆫut","ꆬux", "ꆣuo", "ꆤuop", "ꆢuox",
                            "ꆩe","ꆪep","ꆨex",
                            "ꆳy","ꆴyp","ꆱyt","ꆲyx", "ꆶyr", "ꆵyrx"],
                  re.compile("^hla$"):["ꆠ","ꆡp","ꆞt","ꆟx"],
                  re.compile("^hlap$"):["ꆡ"],
                  re.compile("^hlat$"):["ꆞ"],
                  re.compile("^hlax$"):["ꆟ"],
                  
                  re.compile("^hli$"):["ꆙ","ꆚp","ꆗt","ꆘx", "ꆜe", "ꆝep", "ꆛex"],
                  re.compile("^hlip$"):["ꆚ"],
                  re.compile("^hlit$"):["ꆗ"],
                  re.compile("^hlix$"):["ꆘ"],
                  re.compile("^hlie$"):["ꆜ"],
                  re.compile("^hliep$"):["ꆝ"],
                  re.compile("^hliex$"):["ꆛ"],
                  
                  re.compile("^hlu$"):["ꆭ","ꆮp","ꆫt","ꆬx", "ꆣo", "ꆤop", "ꆢox"],
                  re.compile("^hlup$"):["ꆚ"],
                  re.compile("^hlut$"):["ꆗ"],
                  re.compile("^hlux$"):["ꆘ"],                  
                  re.compile("^hluop$"):["ꆤ"],
                  re.compile("^hluox$"):["ꆢ"],
                
                  re.compile("^hle$"):["ꆩ","ꆪp","ꆨx"],
                  re.compile("^hlep$"):["ꆪ"],
                  re.compile("^hlex$"):["ꆨ"],
                  
                  re.compile("^hly$"):["ꆳ","ꆴp","ꆱt","ꆲx", "ꆶr", "ꆵrx"],
                  re.compile("^hlyp$"):["ꆴ"],
                  re.compile("^hlyt$"):["ꆱ"],
                  re.compile("^hlyx$"):["ꆲ"],
                  re.compile("^hlyr$"):["ꆶ", "ꆵx"],
                  re.compile("^hlyx$"):["ꆵ"],
                  
                  re.compile("^l$"):["ꇁa","ꇂap","ꆿat","ꇀax",
                            "ꆹi","ꆺip","ꆷit","ꆸix","ꆽie","ꆾiep","ꆻiet","ꆼiex",
                            "ꇌe","ꇍep","ꇋex",
                            "ꇐu","ꇑup","ꇎut","ꇏux","ꇓur","ꇒurx","ꇅuo","ꇆuop","ꇃuot","ꇄuox",
                            "ꇖy","ꇗyp","ꇔyt","ꇕyx","ꇙyr","ꇘyrx"],
                  re.compile("^la$"):["ꇁ","ꇂp","ꆿt","ꇀx"],
                  re.compile("^lap$"):["ꇂ"],
                  re.compile("^lat$"):["ꆿ"],
                  re.compile("^lax$"):["ꇀ"],
                  
                  re.compile("^li$"):["ꆹ","ꆺp","ꆷt","ꆸx","ꆽe","ꆾep","ꆻet","ꆼex"],                  
                  re.compile("^lip$"):["ꇂ"],
                  re.compile("^lit$"):["ꆿ"],
                  re.compile("^lix$"):["ꇀ"],
                  re.compile("^lie$"):["ꆽ"],
                  re.compile("^liep$"):["ꆾ"],
                  re.compile("^liet$"):["ꆻ"],
                  re.compile("^liex$"):["ꆼ"],
                  
                  re.compile("^le$"):["ꇌ","ꇍp","ꇋx"],
                  re.compile("^lep$"):["ꇍ"],
                  re.compile("^lex$"):["ꇋ"],
                  
                  re.compile("^lu$"):["ꇐ","ꇑp","ꇎt","ꇏx","ꇓr","ꇒrx","ꇅo","ꇆop","ꇃot","ꇄox"],
                  re.compile("^lup$"):["ꇑ"],
                  re.compile("^lut$"):["ꇎ"],
                  re.compile("^lux$"):["ꇏ"],
                  re.compile("^luo$"):["ꇅ"],
                  re.compile("^lur$"):["ꇓ", "ꇒ"],
                  re.compile("^lurx$"):["ꇒ"],
                  re.compile("^luop$"):["ꇆ"],
                  re.compile("^luot$"):["ꇃ"],
                  re.compile("^luox$"):["ꇄ"],
                  
                  re.compile("^ly$"):["ꇖ","ꇗp","ꇔt","ꇕx","ꇙr","ꇘrx"],
                  re.compile("^lyp$"):["ꇗ"],
                  re.compile("^lyt$"):["ꇔ"],
                  re.compile("^lyx$"):["ꇕ"],
                  re.compile("^lyr$"):["ꇙ", "ꇘx"],
                  re.compile("^lyrx$"):["ꇘ"],
                  re.compile("^g$"):["ꇤa","ꇥap","ꇢat","ꇣax",
                            "ꇜi","ꇝip","ꇚit","ꆸix","ꆽie","ꆾiep","ꆻiet","ꆼiex",
                            "ꇴu","ꇵup","ꇲut","ꇳux","ꇨuo","ꇩuop","ꇦuot","ꇧuox",
                            "ꇰe","ꇱep","ꇮet","ꇯex",
                            "ꇬo","ꇭop","ꇪot","ꇫox"],
                  re.compile("^ga$"):["ꇤ","ꇥp","ꇢt","ꇣx"],
                  re.compile("^gap$"):["ꇥ"],
                  re.compile("^gat$"):["ꇢ"],
                  re.compile("^gax$"):["ꇣ"],
                  
                  re.compile("^gi$"):["ꇜ","ꇝp","ꇚt","ꆸx","ꆽe","ꆾep","ꆻet","ꆼex"],                  
                  re.compile("^gip$"):["ꇂ"],
                  re.compile("^git$"):["ꆿ"],
                  re.compile("^gix$"):["ꇀ"],
                  re.compile("^gie$"):["ꆽ"],
                  re.compile("^giep$"):["ꆾ"],
                  re.compile("^giet$"):["ꆻ"],
                  re.compile("^giex$"):["ꆼ"],
                  
                  re.compile("^gu$"):["ꇴ","ꇵp","ꇲt","ꇳx","ꇨo","ꇩop","ꇦot","ꇧox"],                  
                  re.compile("^gup$"):["ꇵ"],
                  re.compile("^gut$"):["ꇲ"],
                  re.compile("^gux$"):["ꇳ"],
                  re.compile("^guo$"):["ꇨ"],
                  re.compile("^guop$"):["ꇩ"],
                  re.compile("^guot$"):["ꇦ"],
                  re.compile("^guox$"):["ꇧ"],
                  
                  re.compile("^ge$"):["ꇰ","ꇱp","ꇮt","ꇯx"],                  
                  re.compile("^gep$"):["ꇱ"],
                  re.compile("^get$"):["ꇮ"],
                  re.compile("^gex$"):["ꇯ"],
                 
                  re.compile("^go$"):["ꇬ","ꇭp","ꇪt","ꇫx"],
                  re.compile("^gop$"):["ꇭ"],
                  re.compile("^got$"):["ꇪ"],
                  re.compile("^gox$"):["ꇫ"],
                  
                  re.compile("^k$"):["ꈁa","ꈂap","ꇿat","ꈀax",
                            "ꇺi","ꇻip","ꇸit","ꇹix","ꇽie","ꇾiep","ꇼiex",
                            "ꈐu","ꈑup","ꈎut","ꈏux","ꈄuo","ꈅuop","ꈃuox",
                            "ꈌe","ꈍep","ꈊet","ꈋex",
                            "ꈈo","ꈉop","ꈆot","ꈇox"],
                  re.compile("^ka$"):["ꈁ","ꈂp","ꇿt","ꈀx"],
                  re.compile("^kap$"):["ꈂ"],
                  re.compile("^kat$"):["ꇿ"],
                  re.compile("^kax$"):["ꈀ"],
                  
                  re.compile("^ki$"):["ꇺ","ꇻp","ꇸt","ꇹx","ꇽe","ꇾep","ꇼex"],                  
                  re.compile("^kip$"):["ꇻ"],
                  re.compile("^kit$"):["ꇸ"],
                  re.compile("^kix$"):["ꇹ"],
                  re.compile("^kie$"):["ꇽ"],
                  re.compile("^kiep$"):["ꇾ"],
                  re.compile("^kiex$"):["ꇼ"],
                  
                  re.compile("^ku$"):["ꈐ","ꈑp","ꈎt","ꈏx","ꈄo","ꈅop","ꈃox"],                  
                  re.compile("^kup$"):["ꈑ"],
                  re.compile("^kut$"):["ꈎ"],
                  re.compile("^kux$"):["ꈏ"],
                  re.compile("^kuo$"):["ꈄ"],
                  re.compile("^kuop$"):["ꈅ"],
                  re.compile("^kuox$"):["ꈃ"],
                  
                  re.compile("^ke$"):["ꈌ","ꈍp","ꈊt","ꈋx"],                  
                  re.compile("^kep$"):["ꈍ"],
                  re.compile("^ket$"):["ꈊ"],
                  re.compile("^kex$"):["ꈋ"],
                 
                  re.compile("^ko$"):["ꈈ","ꈉp","ꈆt","ꈇx"],
                  re.compile("^kop$"):["ꈉ"],
                  re.compile("^kot$"):["ꈆ"],
                  re.compile("^kox$"):["ꈇ"],
                  
                  re.compile("^gg$"):["ꈜa","ꈝap","ꈚat","ꈛax",
                            "ꇺi","ꈔit","ꈕix","ꈘie","ꈙiep","ꈗiex",
                            "ꈬu","ꈭup","ꈪut","ꈫux","ꈠuo","ꈡuop","ꈞuot","ꈟuox",
                            "ꈨe","ꈩep","ꈦet","ꈧex",
                            "ꈤo","ꈥop","ꈢot","ꈣox"],
                  re.compile("^gga$"):["ꈜ","ꈝp","ꈚt","ꈛx"],
                  re.compile("^ggap$"):["ꈝ"],
                  re.compile("^ggat$"):["ꈚ"],
                  re.compile("^ggax$"):["ꈛ"],
                  
                  re.compile("^ggi$"):["ꇺ","ꈔt","ꈕx","ꈘe","ꈙep","ꈗex"],                  
                  re.compile("^ggit$"):["ꈔ"],
                  re.compile("^ggix$"):["ꈕ"],
                  re.compile("^ggie$"):["ꈘ"],
                  re.compile("^ggiep$"):["ꈙ"],
                  re.compile("^ggiex$"):["ꈗ"],
                  
                  re.compile("^ggu$"):["ꈬ","ꈭp","ꈪt","ꈫx","ꈠo","ꈡop","ꈞot","ꈟox"],                  
                  re.compile("^ggup$"):["ꈭ"],
                  re.compile("^ggut$"):["ꈪ"],
                  re.compile("^ggux$"):["ꈫ"],
                  re.compile("^gguo$"):["ꈠ"],
                  re.compile("^gguop$"):["ꈡ"],
                  re.compile("^gguot$"):["ꈞ"],
                  re.compile("^gguox$"):["ꈟ"],
                  
                  re.compile("^gge$"):["ꈨ","ꈩp","ꈦt","ꈧx"],                  
                  re.compile("^ggep$"):["ꈩ"],
                  re.compile("^gget$"):["ꈦ"],
                  re.compile("^ggex$"):["ꈧ"],
                 
                  re.compile("^ggo$"):["ꈤ","ꈥp","ꈢt","ꈣx"],
                  re.compile("^ggop$"):["ꈥ"],
                  re.compile("^ggot$"):["ꈢ"],
                  re.compile("^ggox$"):["ꈣ"],
                  re.compile("^mg$"):["ꈴa","ꈵap","ꈲat","ꈳax",
                            "ꈱie","ꈰiex",
                            "ꉂu","ꉃup","ꉀut","ꉁux","ꈷuo","ꈸuop","ꈶuox",
                            "ꈾe","ꈿep","ꈽex",
                            "ꈻo","ꈼop","ꈹot","ꈺox"],
                  re.compile("^mga$"):["ꈴ","ꈵp","ꈲt","ꈳx"],
                  re.compile("^mgap$"):["ꈵ"],
                  re.compile("^mgat$"):["ꈲ"],
                  re.compile("^mgax$"):["ꈳ"],
                  
                  re.compile("^mgi$"):["ꈱe","ꈰex"],
                  re.compile("^mgie$"):["ꈱ", "ꈰ"],
                  
                  re.compile("^mgu$"):["ꉂ","ꉃp","ꉀt","ꉁx","ꈷo","ꈸop","ꈶox"],                  
                  re.compile("^mgup$"):["ꉃ"],
                  re.compile("^mgut$"):["ꉀ"],
                  re.compile("^mgux$"):["ꉁ"],
                  re.compile("^mguo$"):["ꈷ"],
                  re.compile("^mguop$"):["ꈸ"],
                  re.compile("^mguox$"):["ꈶ"],
                  
                  re.compile("^mge$"):["ꈾ","ꈿp","ꈽx"],                  
                  re.compile("^mgep$"):["ꈿ"],
                  re.compile("^mgex$"):["ꈽ"],
                 
                  re.compile("^mgo$"):["ꈻ","ꈼp","ꈹt","ꈺx"],
                  re.compile("^mgop$"):["ꈼ"],
                  re.compile("^mgot$"):["ꈹ"],
                  re.compile("^mgox$"):["ꈺ"],
                  
                  re.compile("^hx$"):["ꉐa","ꉑap","ꉎat","ꉏax",
                            "ꉈi","ꉉip","ꉆit","ꉇix","ꉌie","ꉋiex",
                            "ꉛe","ꉜep","ꉚex",
                            "ꉔuo","ꉕuop","ꉒuot","ꉓuox",
                            "ꉘo","ꉙop","ꉖot","ꉗox"],
                  re.compile("^hxa$"):["ꉐ","ꉑp","ꉎt","ꉏx"],
                  re.compile("^hxap$"):["ꉑ"],
                  re.compile("^hxat$"):["ꉎ"],
                  re.compile("^hxax$"):["ꉏ"],
                  
                  re.compile("^hxi$"):["ꉈ","ꉉp","ꉆt","ꉇx","ꉌe","ꉋex"],
                  re.compile("^hxip$"):["ꉉ"],
                  re.compile("^hxit$"):["ꉆ"],
                  re.compile("^hxix$"):["ꉇ"],
                  re.compile("^hxie$"):["ꈱ", "ꈰx"],                
                  re.compile("^hxiex$"):["ꈰ"],
                  
                  re.compile("^hxe$"):["ꉛ","ꉜp","ꉚx"],                  
                  re.compile("^hxep$"):["ꉜ"],
                  re.compile("^hxex$"):["ꉚ"],
                 
                  re.compile("^hxu$"):["ꉔo","ꉕop","ꉒot","ꉓox"],
                  re.compile("^hxuo$"):["ꉔ","ꉕp","ꉒt","ꉓx"],
                  
                  re.compile("^hxo$"):["ꉘ","ꉙp","ꉖt","ꉗx"],
                  re.compile("^hxop$"):["ꉙ"],
                  re.compile("^hxot$"):["ꉖ"],
                  re.compile("^hxox$"):["ꉗ"],
                  re.compile("^ng$"):["ꉢa","ꉣap","ꉠat","ꉡax",
                            "ꉞie","ꉟiep","ꉝiex",
                            "ꉩo","ꉪop","ꉧot","ꉨox",
                            "ꉬe","ꉭep","ꉫex",
                            "ꉦuo","ꉤuot","ꉥuox"],
                  re.compile("^nga$"):["ꉢ","ꉣp","ꉠt","ꉡx"],
                  re.compile("^ngap$"):["ꉣ"],
                  re.compile("^ngat$"):["ꉠ"],
                  re.compile("^ngax$"):["ꉡ"],
                  
                  re.compile("^ngie$"):["ꉞ","ꉟp","ꉝx"],
                  re.compile("^ngiep$"):["ꉟ"],
                  re.compile("^ngiex$"):["ꉝ"],
                  
                  re.compile("^ngo$"):["ꉩ","ꉪp","ꉧt","ꉨx"],
                  re.compile("^ngop$"):["ꉪ"],
                  re.compile("^ngot$"):["ꉧ"],
                  re.compile("^ngox$"):["ꉨ"],
                  
                  re.compile("^nge$"):["ꉬ","ꉭp","ꉫx"],
                  re.compile("^ngep$"):["ꉭ"],
                  re.compile("^ngex$"):["ꉫ"],
                  
                  re.compile("^ngu$"):["ꉦo","ꉤot","ꉥox"],
                  re.compile("^nguo$"):["ꉦ","ꉤt","ꉥx"],
                  re.compile("^nguop$"):["ꉧ"],
                  re.compile("^nguot$"):["ꉨ"],
                  re.compile("^nguox$"):["ꉥ"],
                  
                  re.compile("^h$"):["ꉳa","ꉴap","ꉱat","ꉲax",
                            "ꉮit","ꉰie","ꉯiex",
                            "ꉷuo","ꉸuop","ꉵuot","ꉶuox",
                            "ꉻo", "ꉼop", "ꉹot", "ꉺox",
                            "ꉾe","ꉿep","ꉽex"],
                  re.compile("^ha$"):["ꉳ","ꉴp","ꉱt","ꉲx"],
                  re.compile("^hap$"):["ꉴ"],
                  re.compile("^hat$"):["ꉱ"],
                  re.compile("^hax$"):["ꉲ"],
                  
                  re.compile("^hi$"):["ꉮt","ꉰe","ꉯex"],
                  re.compile("^hie$"):["ꉰ","ꉯx"],
                  re.compile("^hiex$"):["ꉯ"],
                  
                  re.compile("^hu$"):["ꉷo","ꉸop","ꉵot","ꉶox"],
                  re.compile("^huo$"):["ꉷ","ꉸp","ꉵt","ꉶx"],
                  re.compile("^huop$"):["ꉸ"],
                  re.compile("^huot$"):["ꉵ"],
                  re.compile("^huox$"):["ꉶ"],
                  
                  re.compile("^ho$"):["ꉻ", "ꉼp", "ꉹt", "ꉺx"],
                  re.compile("^hop$"):["ꉼ"],
                  re.compile("^hot$"):["ꉹ"],
                  re.compile("^hox$"):["ꉺ"],
                  
                  re.compile("^he$"):["ꉾ","ꉿp","ꉽx"],
                  re.compile("^hep$"):["ꉿ"],
                  re.compile("^hex$"):["ꉽ"],
                  
                  re.compile("^w$"):["ꊂa","ꊂap","ꊀat","ꊁax",
                            "ꊋe","ꊌep","ꊊex",
                            "ꊈo","ꊉop","ꊇox",
                            "ꀕu","ꊅuo","ꊆuop","ꊄuox"],
                  re.compile("^wa$"):["ꊂ","ꊂp","ꊀt","ꊁx"],
                  re.compile("^wap$"):["ꊃ"],
                  re.compile("^wat$"):["ꊀ"],
                  re.compile("^wax$"):["ꊁ"],
                  
                  re.compile("^we$"):["ꊋ","ꊌp","ꊊx"],
                  re.compile("^wep$"):["ꊌ"],
                  re.compile("^wex$"):["ꊊ"],
                  
                  re.compile("^wo$"):["ꊈ","ꊉp","ꊇx"],
                  re.compile("^wop$"):["ꊉ"],
                  re.compile("^wox$"):["ꊇ"],
                  
                  re.compile("^wu$"):["ꀕ","ꊅo","ꊆop","ꊄox"],
                  re.compile("^wuo$"):["ꊅ","ꊆp","ꊄx"],
                  re.compile("^wuop$"):["ꊆ"],
                  re.compile("^wuox$"):["ꊄ"],
                  re.compile("^z$"):["ꊖa","ꊗap","ꊔat","ꊕax",
                            "ꊏit","ꊒie","ꊓiep","ꊑix",
                            "ꊤu", "ꊥup", "ꊢut", "ꊣux", "ꊧur", "ꊦurx","ꊙuo", "ꊚuop", "ꊘuox",
                            "ꊠe","ꊡep", "ꊟex",
                            "ꊝo","ꊞop","ꊛot","ꊜox",
                            "ꊪy", "ꊫyp", "ꊨyt", "ꊩyx", "ꊭyr", "ꊬyrx"],
                  re.compile("^za$"):["ꊖ","ꊗp","ꊔt","ꊕx"],
                  re.compile("^zap$"):["ꊗ"],
                  re.compile("^zat$"):["ꊔ"],
                  re.compile("^zax$"):["ꊕ"],
                  
                  re.compile("^zi$"):["ꊏt","ꊒe","ꊓep","ꊑx"],
                  re.compile("^zie$"):["ꊒ","ꊓp","ꉯx"],
                  re.compile("^ziep$"):["ꊓ"],
                  re.compile("^ziex$"):["ꊑ"],
                  
                  re.compile("^zu$"):["ꊤ", "ꊥp", "ꊢt", "ꊣx", "ꊧr", "ꊦrx","ꊙo", "ꊚop", "ꊘox"],
                  re.compile("^zup$"):["ꊥ"],
                  re.compile("^zut$"):["ꊢ"],
                  re.compile("^zux$"):["ꊣ"],
                  re.compile("^zur$"):["ꊧ", "ꊦx"],
                  re.compile("^zurx$"):["ꊦ"],
                  re.compile("^zuo$"):["ꊙ", "ꊚp", "ꊘx"],
                  re.compile("^zuop$"):["ꊚ"],
                  re.compile("^zuox$"):["ꊘ"],
                  
                  re.compile("^ze$"):["ꊠ","ꊡp", "ꊟx"],
                  re.compile("^zep$"):["ꊡ"],
                  re.compile("^zex$"):["ꊟ"],
                  
                  re.compile("^zo$"):["ꊝ","ꊞp","ꊛt","ꊜx"],
                  re.compile("^zop$"):["ꊞ"],
                  re.compile("^zot$"):["ꊛ"],
                  re.compile("^zox$"):["ꊜ"],
                  
                  re.compile("^zy$"):["ꊪ", "ꊫp", "ꊨt", "ꊩx", "ꊭr", "ꊬrx"],
                  re.compile("^zyp$"):["ꊫ"],
                  re.compile("^zyt$"):["ꊨ"],
                  re.compile("^zyx$"):["ꊩ"],
                  re.compile("^zyr$"):["ꊭ", "ꊬx"],
                  re.compile("^zyrx$"):["ꊬ"],
                  
                  re.compile("^c$"):["ꊖa","ꊗap","ꊔat","ꊕax",
                            "ꊏit","ꊒie","ꊓiep","ꊑiex",
                            "ꋆu", "ꋇup", "ꋄut", "ꋅux", "ꋉur", "ꋈurx","ꊻuo", "ꊼuop", "ꊺuox",
                            "ꋂe","ꋃep","ꋁex",
                            "ꊿo","ꋀop","ꊽot","ꊾox",
                            "ꋌy", "ꋍyp", "ꋊyt", "ꋋyx", "ꋏyr", "ꋎyrx"],
                  re.compile("^ca$"):["ꊖ","ꊗp","ꊔt","ꊕx"],
                  re.compile("^cap$"):["ꊗ"],
                  re.compile("^cat$"):["ꊔ"],
                  re.compile("^cax$"):["ꊕ"],
                  
                  re.compile("^ci$"):["ꊏt","ꊒe","ꊓep","ꊑex"],
                  re.compile("^cit$"):["ꊏ"],
                  re.compile("^cie$"):["ꊒ","ꊓp","ꉯx"],
                  re.compile("^ciep$"):["ꊓ"],
                  re.compile("^ciex$"):["ꊑ"],
                  
                  re.compile("^cu$"):["ꋆ", "ꋇp", "ꋄt", "ꋅx", "ꋉr", "ꋈrx","ꊻo", "ꊼop", "ꊺox"],
                  re.compile("^cup$"):["ꋇ"],
                  re.compile("^cut$"):["ꋄ"],
                  re.compile("^cux$"):["ꋅ"],
                  re.compile("^cur$"):["ꋉ", "ꋈx"],
                  re.compile("^curx$"):["ꋈ"],
                  re.compile("^cuo$"):["ꊻ", "ꊼp", "ꊺx"],
                  re.compile("^cuop$"):["ꊼ"],
                  re.compile("^cuox$"):["ꊺ"],
                  
                  re.compile("^ce$"):["ꋂ","ꋃp", "ꋁx"],
                  re.compile("^cep$"):["ꋃ"],
                  re.compile("^cex$"):["ꋁ"],
                  
                  re.compile("^co$"):["ꊿ","ꋀp","ꊽt","ꊾx"],
                  re.compile("^cop$"):["ꋀ"],
                  re.compile("^cot$"):["ꊽ"],
                  re.compile("^cox$"):["ꊾ"],
                  
                  re.compile("^cy$"):["ꋌ", "ꋍp", "ꋊt", "ꋋx", "ꋏr", "ꋎrx"],
                  re.compile("^cyp$"):["ꋍ"],
                  re.compile("^cyt$"):["ꋊ"],
                  re.compile("^cyx$"):["ꋋ"],
                  re.compile("^cyr$"):["ꋏ", "ꋋx"],
                  re.compile("^cyrx$"):["ꋎ"],
                  
                  re.compile("zz$"):["ꋚa","ꋛap","ꋘat","ꋙax",
                            "ꋒi","ꋓip","ꋐt","ꋑx","ꋖe", "ꋗep", "ꋔet", "ꋕex",
                            "ꋣu", "ꋤup", "ꋢux", "ꋦur", "ꋥurx",
                            "ꋠe","ꋡep", "ꋟex",
                            "ꋝo","ꋞop","ꋜox",
                            "ꋩy", "ꋪyp", "ꋧyt", "ꋨyx", "ꋬyr", "ꋫyrx"],
                            
                  re.compile("^zza$"):["ꋚ","ꋛp","ꋘt","ꋙx"],
                  re.compile("^zzap$"):["ꋛ"],
                  re.compile("^zzat$"):["ꋘ"],
                  re.compile("^zzax$"):["ꋙ"],
                  
                  re.compile("^zzi$"):["ꋒ","ꋓp","ꋐt","ꋑx","ꋖe", "ꋗep", "ꋔet", "ꋕex"],
                  re.compile("^zzip$"):["ꋓ"],
                  re.compile("^zzit$"):["ꋐ"],
                  re.compile("^zzix$"):["ꋑ"],
                  re.compile("^zzie$"):["ꋖ","ꋗp", "ꋔt","ꋕx"],
                  re.compile("^zziet$"):["ꋔ"],
                  re.compile("^zziep$"):["ꊓ"],                  
                  re.compile("^zziex$"):["ꊑ"],
                  
                  re.compile("^zzu$"):["ꋣ", "ꋤp", "ꋢx", "ꋦr", "ꋥrx"],
                  re.compile("^zzup$"):["ꋤ"],
                  re.compile("^zzux$"):["ꋢ"],
                  re.compile("^zzur$"):["ꋦ", "ꋥx"],
                  re.compile("^zzurx$"):["ꋥ"],
                  
                  re.compile("^zze$"):["ꋠ","ꋡp", "ꋟx"],
                  re.compile("^zzep$"):["ꋡ"],
                  re.compile("^zzex$"):["ꋟ"],
                  
                  re.compile("^zzo$"):["ꋝ","ꋞp","ꋜx"],
                  re.compile("^zzop$"):["ꋞ"],
                  re.compile("^zzox$"):["ꋜ"],
                  
                  re.compile("^zzy$"):["ꋩ", "ꋪp", "ꋧt", "ꋨx", "ꋬr", "ꋫrx"],
                  re.compile("^zzyp$"):["ꋪ"],
                  re.compile("^zzyt$"):["ꋧ"],
                  re.compile("^zzyx$"):["ꋨ"],
                  re.compile("^zzyr$"):["ꋬ", "ꋫx"],
                  re.compile("^zzyrx$"):["ꋫ"],
                  
                  
                  
                  re.compile("^nz$"):["ꋶa","ꋷap","ꋴat","ꋵax",
                            "ꋯi","ꋰip","ꋭit","ꋮix","ꋲie", "ꋳiep", "ꋱiex",
                            "ꋿu", "ꌀup", "ꋾux", "ꌂur", "ꌁurx", "ꋹuo", "ꋸuox",
                            "ꋽe","ꋼex",
                            "ꋻop","ꋺox",
                            "ꌅy", "ꌆyp", "ꌃyt", "ꌄyx", "ꌈyr", "ꌇyrx"],
                  
                  re.compile("^nza$"):["ꋶ","ꋷp","ꋴt","ꋵx"],
                  re.compile("^nzap$"):["ꋷ"],
                  re.compile("^nzat$"):["ꋴ"],
                  re.compile("^nzax$"):["ꋵ"],
                  
                  re.compile("^nzi$"):["ꋯ","ꋰp","ꋭt","ꋮx","ꋲe", "ꋳep", "ꋱex"],
                  re.compile("^nzip$"):["ꋰ"],
                  re.compile("^nzit$"):["ꋭ"],
                  re.compile("^nzix$"):["ꋮ"],
                  re.compile("^nzie$"):["ꋲ","ꋳp", "ꋱx"],
                  re.compile("^nziet$"):["ꋔ"],
                  re.compile("^nziep$"):["ꊓ"],                  
                  re.compile("^nziex$"):["ꊑ"],
                  
                  re.compile("^nzu$"):["ꋿ", "ꌀp", "ꋾx", "ꌂr", "ꌁrx", "ꋹo", "ꋸox"],
                  re.compile("^nzup$"):["ꌀ"],
                  re.compile("^nzux$"):["ꋾ"],
                  re.compile("^nzur$"):["ꌂ", "ꌁx"],
                  re.compile("^nzurx$"):["ꌁ"],
                  re.compile("^nzuo$"):["ꋹ","ꋸx"],
                  re.compile("^nzuox$"):["ꋸ"],
                  
                  re.compile("^nze$"):["ꋽ","ꋼx"],
                  re.compile("^nzex$"):["ꋼ"],
                  
                  re.compile("^nzo$"):["ꋻp","ꋺx"],
                  re.compile("^nzop$"):["ꋻ"],
                  re.compile("^nzox$"):["ꋺ"],
                  
                  re.compile("^nzy$"):["ꌅ", "ꌆp", "ꌃt", "ꌄx", "ꌈr", "ꌇrx"],
                  re.compile("^nzyp$"):["ꌆ"],
                  re.compile("^nzyt$"):["ꌃ"],
                  re.compile("^nzyx$"):["ꌄ"],
                  re.compile("^nzyr$"):["ꌈ", "ꌇx"],
                  re.compile("^nzyrx$"):["ꌇ"],
                  re.compile("^s$"):["ꌒa","ꌓap","ꌐat","ꌑax",
                            "ꌋi","ꌌip","ꌉit","ꌊix","ꌎie", "ꌏiep", "ꌍiex",
                            "ꌠu", "ꌡup", "ꌟux", "ꌣur", "ꌢurx", "ꌙuo", "ꌚuop", "ꌘuox",
                            "ꌜe", "ꌝep", "ꌛex",
                            "ꌙo", "ꌚop", "ꌗot","ꌘox",
                            "ꌦy", "ꌧyp", "ꌤyt", "ꌥyx", "ꌩyr", "ꌨyrx"],
                            
                  re.compile("^sa$"):["ꌒ","ꌓp","ꌐt","ꌑx"],
                  re.compile("^sap$"):["ꌓ"],
                  re.compile("^sat$"):["ꌐ"],
                  re.compile("^sax$"):["ꌑ"],
                  
                  re.compile("^si$"):["ꌋ","ꌌp","ꌉt","ꌊx","ꌎe", "ꌏep", "ꌍex"],
                  re.compile("^sie$"):["ꌎ","ꌏp", "ꌍx"],
                  re.compile("^siep$"):["ꌏ"],                  
                  re.compile("^siex$"):["ꌍ"],
                  
                  re.compile("^su$"):["ꌠ", "ꌡp", "ꌟx", "ꌣr", "ꌢrx", "ꌙo", "ꌚop", "ꌘox"],
                  re.compile("^sup$"):["ꌡ"],
                  re.compile("^sux$"):["ꌟ"],
                  re.compile("^sur$"):["ꌣ", "ꌢx"],
                  re.compile("^surx$"):["ꌢ"],
                  re.compile("^suo$"):["ꌕ", "ꌖp","ꌔx"],
                  re.compile("^suop$"):["ꌖ"],
                  re.compile("^suox$"):["ꌔ"],
                  
                  re.compile("^se$"):["ꌜ", "ꌝp", "ꌛx"],
                  re.compile("^sep$"):["ꌝ"],
                  re.compile("^sex$"):["ꌛ"],
                  
                  re.compile("^so$"):["ꌙ", "ꌚp", "ꌗt","ꌘx"],
                  re.compile("^sop$"):["ꌚ"],
                  re.compile("^sot$"):["ꌗ"],
                  re.compile("^sox$"):["ꌘ"],
                  
                  re.compile("^sy$"):["ꌦ", "ꌧp", "ꌤt", "ꌥx", "ꌩr", "ꌨrx"],
                  re.compile("^syp$"):["ꌧ"],
                  re.compile("^syt$"):["ꌤ"],
                  re.compile("^syx$"):["ꌥ"],
                  re.compile("^syr$"):["ꌩ", "ꌨx"],
                  re.compile("^syrx$"):["ꌨ"],
                  
                  re.compile("^ss$"):["ꌳa","ꌴap","ꌱat","ꌲax",
                            "ꌬi","ꌭip","ꌪit","ꌫix","ꌯie", "ꌰiep", "ꌮiex",
                            "ꌾu", "ꌿup", "ꌼut" ,"ꌽux",
                            "ꌺe", "ꌻep", "ꌹex",
                            "ꌷo", "ꌸop", "ꌵot","ꌶox",
                            "ꍂy", "ꍃyp", "ꍀyt", "ꍁyx", "ꍅyr", "ꍄyrx"],
                  re.compile("^ssa$"):["ꌳ","ꌴp","ꌱt","ꌲx"],
                  re.compile("^ssap$"):["ꌴ"],
                  re.compile("^ssat$"):["ꌱ"],
                  re.compile("^ssax$"):["ꌲ"],
                  
                  re.compile("^ssi$"):["ꌬ","ꌭp","ꌪt","ꌫx","ꌯe", "ꌰep", "ꌮex"],
                  re.compile("^ssie$"):["ꌯ","ꌰp","ꌮx"],
                  re.compile("^ssiep$"):["ꌰ"],                  
                  re.compile("^ssiex$"):["ꌮ"],
                  
                  re.compile("^ssu$"):["ꌾ", "ꌿp", "ꌼt" ,"ꌽx"],
                  re.compile("^ssup$"):["ꌿ"],
                  re.compile("^ssut$"):["ꌼ"],
                  re.compile("^ssux$"):["ꌽ"],
                  
                  re.compile("^sse$"):["ꌺ", "ꌻp", "ꌹx"],
                  re.compile("^ssep$"):["ꌻ"],
                  re.compile("^ssex$"):["ꌹ"],
                  
                  re.compile("^sso$"):["ꌷ", "ꌸp", "ꌵt","ꌶx"],
                  re.compile("^ssop$"):["ꌸ"],
                  re.compile("^ssot$"):["ꌵ"],
                  re.compile("^ssox$"):["ꌶ"],
                  
                  re.compile("^ssy$"):["ꍂ", "ꍃp", "ꍀt", "ꍁx", "ꍅr", "ꍄrx"],
                  re.compile("^ssyp$"):["ꍃ"],
                  re.compile("^ssyt$"):["ꍀ"],
                  re.compile("^ssyx$"):["ꍁ"],
                  re.compile("^ssyr$"):["ꍅ", "ꍄx"],
                  re.compile("^ssyrx$"):["ꍄ"],
                  
                  re.compile("^zh$"):["ꍈa","ꍉap","ꍆat","ꍇax",
                            "ꍗu", "ꍘup", "ꍕut" ,"ꍖux", "ꍚur", "ꍙurx", "ꍋuo", "ꍌuop", "ꍊuox",
                            "ꍓe", "ꍔep", "ꍑet", "ꍒex",
                            "ꍏo", "ꍐop", "ꍍot", "ꍎox",
                            "ꍝy", "ꍞyp", "ꍛyt", "ꍜyx", "ꍠyr", "ꍟyrx"],
                  re.compile("^zha$"):["ꍈ","ꍉp","ꍆt","ꍇx"],
                  re.compile("^zhap$"):["ꍉ"],
                  re.compile("^zhat$"):["ꍆ"],
                  re.compile("^zhax$"):["ꍇ"],

                  
                  re.compile("^zhu$"):["ꍗ", "ꍘp", "ꍕt" ,"ꍖx", "ꍚr", "ꍙrx", "ꍋo", "ꍌop", "ꍊox"],
                  re.compile("^zhup$"):["ꌿ"],
                  re.compile("^zhut$"):["ꌼ"],
                  re.compile("^zhux$"):["ꌽ"],
                  re.compile("^zhur$"):["ꍚ", "ꍙx"],
                  re.compile("^zhurx$"):["ꍙ"],
                  re.compile("^zhuo$"):["ꍋ", "ꍌp", "ꍊx"],
                  re.compile("^zhuop$"):["ꍌ"],
                  re.compile("^zhuox$"):["ꍊ"],
                  
                  
                  re.compile("^zhe$"):["ꍓ", "ꍔp", "ꍑt", "ꍒx"],
                  re.compile("^zhep$"):["ꌻ"],
                  re.compile("^zhet$"):["ꍑ"],
                  re.compile("^zhex$"):["ꌹ"],
                  
                  re.compile("^zho$"):["ꍏ", "ꍐp", "ꍍt", "ꍎx"],
                  re.compile("^zhop$"):["ꍐ"],
                  re.compile("^zhot$"):["ꍍ"],
                  re.compile("^zhox$"):["ꍎ"],
                  
                  re.compile("^zhy$"):["ꍝ", "ꍞp", "ꍛt", "ꍜx", "ꍠr", "ꍟrx"],
                  re.compile("^zhyp$"):["ꍞ"],
                  re.compile("^zhyt$"):["ꍛ"],
                  re.compile("^zhyx$"):["ꍜ"],
                  re.compile("^zhyr$"):["ꍠ", "ꍟx"],
                  re.compile("^zhyrx$"):["ꍟ"],
                  
                  re.compile("^ch$"):["ꍣa","ꍤap","ꍡat","ꍢax",
                            "ꍲu", "ꍳup", "ꍱux", "ꍵur", "ꍴurx", "ꍫuo", "ꍬuop", "ꍥuot","ꍦuox",
                            "ꍯe", "ꍰep", "ꍭet", "ꍮex",
                            "ꍫo", "ꍬop", "ꍩot", "ꍪox",
                            "ꍸy", "ꍹyp", "ꍶyt", "ꍷyx", "ꍻyr", "ꍺyrx"],
                  re.compile("^cha$"):["ꍣ","ꍤp","ꍡt","ꍢx"],
                  re.compile("^chap$"):["ꍤ"],
                  re.compile("^chat$"):["ꍡ"],
                  re.compile("^chax$"):["ꍢ"],

                  
                  re.compile("^chu$"):["ꍲ", "ꍳp", "ꍱx", "ꍵr", "ꍴrx", "ꍫo", "ꍬop", "ꍥot","ꍦox"],
                  re.compile("^chup$"):["ꍳ"],
                  re.compile("^chux$"):["ꍱ"],
                  re.compile("^chur$"):["ꍵ", "ꍴx"],
                  re.compile("^churx$"):["ꍴ"],
                  re.compile("^chuo$"):["ꍧ", "ꍨp", "ꍦx"],
                  re.compile("^chuop$"):["ꍨ"],
                  re.compile("^chuox$"):["ꍦ"],
                  
                  
                  re.compile("^che$"):["ꍯ", "ꍰp", "ꍭt", "ꍮx"],
                  re.compile("^chep$"):["ꍰ"],
                  re.compile("^chet$"):["ꍭ"],
                  re.compile("^chex$"):["ꍮ"],
                  
                  re.compile("^cho$"):["ꍫ", "ꍬp", "ꍩt", "ꍪx"],
                  re.compile("^chop$"):["ꍬ"],
                  re.compile("^chot$"):["ꍩ"],
                  re.compile("^chox$"):["ꍪ"],
                  
                  re.compile("^chy$"):["ꍸ", "ꍹp", "ꍶt", "ꍷx", "ꍻr", "ꍺrx"],
                  re.compile("^chyp$"):["ꍹ"],
                  re.compile("^chyt$"):["ꍶ"],
                  re.compile("^chyx$"):["ꍷ"],
                  re.compile("^chyr$"):["ꍻ", "ꍺx"],
                  re.compile("^chyrx$"):["ꍺ"],
                  
                  re.compile("^rr$"):["ꍽa","ꍼax",
                            "ꎊu", "ꎋup", "ꍥut", "ꎉux", "ꎍur", "ꎌurx", "ꍿuo", "ꍾuox",
                            "ꎆe", "ꎇep", "ꎄet", "ꎅex",
                            "ꎂo", "ꎃop", "ꎀot", "ꎁox",
                            "ꎐy", "ꎑyp", "ꎎyt", "ꎏyx", "ꎓyr", "ꎒyrx"],
                            
                  re.compile("^rra$"):["ꍽ","ꍼx"],
                  re.compile("^rrax$"):["ꍼ"],

                  
                  re.compile("^rru$"):["ꎊ", "ꎋp", "ꍥt", "ꎉx", "ꎍr", "ꎌrx", "ꍿo", "ꍾox"],
                  re.compile("^rrup$"):["ꎋ"],
                  re.compile("^rrut$"):["ꎈ"],
                  re.compile("^rrux$"):["ꎉ"],
                  re.compile("^rrur$"):["ꎍ", "ꎌx"],
                  re.compile("^rrurx$"):["ꎌ"],
                  re.compile("^rruo$"):["ꍿ", "ꍾx"],
                  re.compile("^rruox$"):["ꍾ"],
                  
                  
                  re.compile("^rre$"):["ꎆ", "ꎇp", "ꎄt", "ꎅx"],
                  re.compile("^rrep$"):["ꎇ"],
                  re.compile("^rret$"):["ꎄ"],
                  re.compile("^rrex$"):["ꎅ"],
                  
                  re.compile("^rro$"):["ꎂ", "ꎃp", "ꎀt", "ꎁx"],
                  re.compile("^rrop$"):["ꎃ"],
                  re.compile("^rrot$"):["ꎀ"],
                  re.compile("^rrox$"):["ꎁ"],
                  
                  re.compile("^rry$"):["ꎐ", "ꎑp", "ꎎt", "ꎏx", "ꎓr", "ꎒrx"],
                  re.compile("^rryp$"):["ꎑ"],
                  re.compile("^rryt$"):["ꎎ"],
                  re.compile("^rryx$"):["ꎏ"],
                  re.compile("^rryr$"):["ꎓ", "ꎒx"],
                  re.compile("^rryrx$"):["ꎒ"],
                  
                  re.compile("^nr$"):["ꎖa","ꎗap","ꎔat","ꎕax",
                            "ꎡu", "ꎢup", "ꎟut", "ꎠux", "ꎤur", "ꎣurx",
                            "ꎝe", "ꎞep", "ꎛet", "ꎜex",
                            "ꎙo", "ꎚop", "ꎘox",
                            "ꎧy", "ꎨyp", "ꎥyt", "ꎦyx", "ꎪyr", "ꎩyrx"],
                  re.compile("^nra$"):["ꎖ","ꎗp","ꎔt","ꎕx"],
                  re.compile("^nrap$"):["ꎗ"],
                  re.compile("^nrat$"):["ꎔ"],
                  re.compile("^nrax$"):["ꎕ"],

                  
                  re.compile("^nru$"):["ꎡ", "ꎢp", "ꎟt", "ꎠx", "ꎤr", "ꎣrx"],
                  re.compile("^nrup$"):["ꎢ"],
                  re.compile("^nrut$"):["ꎟ"],
                  re.compile("^nrux$"):["ꎠ"],
                  re.compile("^nrur$"):["ꎤ", "ꎣx"],
                  re.compile("^nrurx$"):["ꎣ"],
                  
                  
                  re.compile("^nre$"):["ꎝ", "ꎞp", "ꎛt", "ꎜx"],
                  re.compile("^nrep$"):["ꎞ"],
                  re.compile("^nret$"):["ꎛ"],
                  re.compile("^nrex$"):["ꎜ"],
                  
                  re.compile("^nro$"):["ꎙ", "ꎚp", "ꎘx"],
                  re.compile("^nrop$"):["ꎚ"],
                  re.compile("^nrox$"):["ꎘ"],
                  
                  re.compile("^nry$"):["ꎧ", "ꎨp", "ꎥt", "ꎦx", "ꎪr", "ꎩrx"],
                  re.compile("^nryp$"):["ꎨ"],
                  re.compile("^nryt$"):["ꎥ"],
                  re.compile("^nryx$"):["ꎦ"],
                  re.compile("^nryr$"):["ꎪ", "ꎩx"],
                  re.compile("^nryrx$"):["ꎩ"],
                  
                  re.compile("^sh$"):["ꎭa","ꎮap","ꎫat","ꎬax",
                            "ꎼu", "ꎽup", "ꎺut", "ꎻux", "ꎿur", "ꎾurx",
                            "ꎸe", "ꎹep", "ꎶet", "ꎷex",
                            "ꎴo", "ꎵop", "ꎲot", "ꎳox",
                            "ꏂy", "ꏃyp", "ꏀyt", "ꏁyx", "ꏅyr", "ꎾyrx"],
                            
                  re.compile("^sha$"):["ꎭ","ꎮp","ꎫt","ꎬx"],
                  re.compile("^shap$"):["ꎮ"],
                  re.compile("^shat$"):["ꎫ"],
                  re.compile("^shax$"):["ꎬ"],

                  
                  re.compile("^shu$"):["ꎼ", "ꎽp", "ꎺt", "ꎻx", "ꎿr", "ꎾrx"],
                  re.compile("^shup$"):["ꎽ"],
                  re.compile("^shut$"):["ꎺ"],
                  re.compile("^shux$"):["ꎻ"],
                  re.compile("^shur$"):["ꎿ", "ꎾx"],
                  re.compile("^shurx$"):["ꎾ"],
                  
                  
                  re.compile("^she$"):["ꎸ", "ꎹp", "ꎶt", "ꎷx"],
                  re.compile("^shep$"):["ꎹ"],
                  re.compile("^shet$"):["ꎶ"],
                  re.compile("^shex$"):["ꎷ"],
                  
                  re.compile("^sho$"):["ꎴ", "ꎵp", "ꎲt", "ꎳx"],
                  re.compile("^shop$"):["ꎵ"],
                  re.compile("^shot$"):["ꎲ"],
                  re.compile("^shox$"):["ꎳ"],
                  
                  re.compile("^shy$"):["ꏂ", "ꏃp", "ꏀt", "ꏁx", "ꏅr", "ꎾrx"],
                  re.compile("^shyp$"):["ꏃ"],
                  re.compile("^shyt$"):["ꏀ"],
                  re.compile("^shyx$"):["ꏁ"],
                  re.compile("^shyr$"):["ꏅ", "ꏄx"],
                  re.compile("^shyrx$"):["ꏄ"],
                  
                  re.compile("^r$"):["ꏈa","ꏉap","ꏆat","ꏇax",
                            "ꏖu", "ꏗup", "ꏔut", "ꏕux", "ꏙur", "ꏘurx",
                            "ꏒe", "ꏓep", "ꏑex",
                            "ꏏo", "ꏐop", "ꏍot", "ꏎox",
                            "ꏜy", "ꏝyp", "ꏚyt", "ꏛyx", "ꏟyr", "ꏞyrx"],
                  re.compile("^ra$"):["ꏈ","ꏉp","ꏆt","ꏇx"],
                  re.compile("^rap$"):["ꏉ"],
                  re.compile("^rat$"):["ꏆ"],
                  re.compile("^rax$"):["ꏇ"],

                  
                  re.compile("^ru$"):["ꏖ", "ꏗp", "ꏔt", "ꏕx", "ꏙr", "ꏘrx"],
                  re.compile("^rup$"):["ꏗ"],
                  re.compile("^rut$"):["ꏔ"],
                  re.compile("^rux$"):["ꏕ"],
                  re.compile("^rur$"):["ꏙ", "ꏘx"],
                  re.compile("^rurx$"):["ꏘ"],
                  
                  
                  re.compile("^re$"):["ꏒ", "ꏓp", "ꏑx"],
                  re.compile("^rep$"):["ꏓ"],
                  re.compile("^rex$"):["ꏑ"],
                  
                  re.compile("^ro$"):["ꏏ", "ꏐp", "ꏍt", "ꏎx"],
                  re.compile("^rop$"):["ꏐ"],
                  re.compile("^rot$"):["ꏍ"],
                  re.compile("^rox$"):["ꏎ"],
                  
                  re.compile("^ry$"):["ꏜ", "ꏝp", "ꏚt", "ꏛx", "ꏟr", "ꏞrx"],
                  re.compile("^ryp$"):["ꏝ"],
                  re.compile("^ryt$"):["ꏚ"],
                  re.compile("^ryx$"):["ꏛ"],
                  re.compile("^ryr$"):["ꏟ", "ꏞx"],
                  re.compile("^ryrx$"):["ꏞ"],
                  
                  re.compile("^j$"):["ꏢi","ꏣip","ꏠit","ꏡix","ꏦie", "ꏧiep", "ꏤiet", "ꏥiex",
                            "ꏲu", "ꏳup", "ꏰut", "ꏱux", "ꏵur", "ꏴurx", "ꏪuo", "ꏫuop", "ꏨuot", "ꏩuox",
                            "ꏮo", "ꏯop", "ꏬot", "ꏭox",
                            "ꏸy", "ꏹyp", "ꏶyt", "ꏷyx", "ꏻyr", "ꏺyrx"],
                  re.compile("^ji$"):["ꏢ","ꏣp","ꏠt","ꏡx","ꏦe", "ꏧep", "ꏤet", "ꏥex"],
                  re.compile("^jip$"):["ꏣ"],
                  re.compile("^jit$"):["ꏠ"],
                  re.compile("^jix$"):["ꏡ"],                  
                  re.compile("^jie$"):["ꏦ", "ꏧp", "ꏤt", "ꏥx"],
                  re.compile("^jiep$"):["ꏧ"],
                  re.compile("^jiet$"):["ꏤ"],
                  re.compile("^jiex$"):["ꏥ"],

                  
                  re.compile("^ju$"):["ꏲ", "ꏳp", "ꏰt", "ꏱx", "ꏵr", "ꏴrx", "ꏪo", "ꏫop", "ꏨot", "ꏩox"],
                  re.compile("^jup$"):["ꏳ"],
                  re.compile("^jut$"):["ꏰ"],
                  re.compile("^jux$"):["ꏱ"],
                  re.compile("^jur$"):["ꏵ", "ꏴx"],
                  re.compile("^jurx$"):["ꏴ"],
                  re.compile("^juo$"):["ꏪ", "ꏫp", "ꏨt", "ꏩx"],
                  re.compile("^juop$"):["ꏫ"],
                  re.compile("^juot$"):["ꏨ"],
                  re.compile("^juox$"):["ꏩ"],
                 
                  
                  re.compile("^jo$"):["ꏮ", "ꏯp", "ꏬt", "ꏭx"],
                  re.compile("^jop$"):["ꏯ"],
                  re.compile("^jot$"):["ꏬ"],
                  re.compile("^jox$"):["ꏭ"],
                  
                  re.compile("^jy$"):["ꏸ", "ꏹp", "ꏶt", "ꏷx", "ꏻr", "ꏺrx"],
                  re.compile("^jyp$"):["ꏹ"],
                  re.compile("^jyt$"):["ꏶ"],
                  re.compile("^jyx$"):["ꏷ"],
                  re.compile("^jyr$"):["ꏻ", "ꏺx"],
                  re.compile("^jyrx$"):["ꏺ"],
                  
                  re.compile("^q$"):["ꏾi","ꏿip","ꏼit","ꏽix","ꐂie", "ꐃiep", "ꐀiet", "ꐁiex",
                            "ꐎu", "ꐏup", "ꐌut", "ꐍux", "ꐑur", "ꐐurx", "ꐆuo", "ꐇuop", "ꐄuot", "ꐅuox",
                            "ꐊo", "ꐋop", "ꐈot", "ꐉox",
                            "ꐔy", "ꐕyp", "ꐒyt", "ꐓyx", "ꐗyr", "ꐖyrx"],
                  re.compile("^qi$"):["ꏾ","ꏿp","ꏼt","ꏽx","ꐂe", "ꐃep", "ꐀet", "ꐁex"],
                  re.compile("^qip$"):["ꏿ"],
                  re.compile("^qit$"):["ꏼ"],
                  re.compile("^qix$"):["ꏽ"],                  
                  re.compile("^qie$"):["ꐂ", "ꐃp", "ꐀt", "ꐁx"],
                  re.compile("^qiep$"):["ꐃ"],
                  re.compile("^qiet$"):["ꐀ"],
                  re.compile("^qiex$"):["ꐁ"],

                  
                  re.compile("^qu$"):["ꐎ", "ꐏp", "ꐌt", "ꐍx", "ꐑr", "ꐐrx", "ꐆo", "ꐇop", "ꐄot", "ꐅox"],
                  re.compile("^qup$"):["ꐏ"],
                  re.compile("^qut$"):["ꐌ"],
                  re.compile("^qux$"):["ꐍ"],
                  re.compile("^qur$"):["ꐑ", "ꐐx"],
                  re.compile("^qurx$"):["ꐐ"],
                  re.compile("^quo$"):["ꐆ", "ꐇp","ꐄt", "ꐅx" ],
                  re.compile("^quop$"):["ꐇ"],
                  re.compile("^quot$"):["ꐄ"],
                  re.compile("^quox$"):["ꐅ"],
                 
                  
                  re.compile("^qo$"):["ꐊ", "ꐋp", "ꐈt", "ꐉx"],
                  re.compile("^qop$"):["ꐋ"],
                  re.compile("^qot$"):["ꐈ"],
                  re.compile("^qox$"):["ꐉ"],
                  
                  re.compile("^qy$"):["ꐔ", "ꐕp", "ꐒt", "ꐓx", "ꐗr", "ꐖrx"],
                  re.compile("^qyp$"):["ꐕ"],
                  re.compile("^qyt$"):["ꐒ"],
                  re.compile("^qyx$"):["ꐓ"],
                  re.compile("^qyr$"):["ꐗ", "ꐖx"],
                  re.compile("^qyrx$"):["ꐖ"],
                  
                  
                  re.compile("^jj$"):["ꐚi","ꐛip","ꐘit","ꐙix","ꐞie", "ꐟiep", "ꐜiet", "ꐝiex",
                            "ꐩu", "ꐪup", "ꐧut", "ꐨux", "ꐬur", "ꐫurx", "ꐥuo", "ꐦuop", "ꐣuot", "ꐤuox",
                            "ꐥo", "ꐦop", "ꐣot", "ꐤox",
                            "ꐯy", "ꐰyp", "ꐭyt", "ꐮyx"],
                  re.compile("^jji$"):["ꐚ","ꐛp","ꐘt","ꐙx","ꐞe", "ꐟep", "ꐜet", "ꐝex"],
                  re.compile("^jjip$"):["ꐛ"],
                  re.compile("^jjit$"):["ꐘ"],
                  re.compile("^jjix$"):["ꐙ"],                  
                  re.compile("^jjie$"):["ꐞ", "ꐟp", "ꐜt", "ꐝx"],
                  re.compile("^jjiep$"):["ꐟ"],
                  re.compile("^jjiet$"):["ꐜ"],
                  re.compile("^jjiex$"):["ꐝ"],

                  
                  re.compile("^jju$"):["ꐩ", "ꐪp", "ꐧt", "ꐨx", "ꐬr", "ꐫrx", "ꐥo", "ꐦop", "ꐣot", "ꐤox"],
                  re.compile("^jjup$"):["ꐪ"],
                  re.compile("^jjut$"):["ꐧ"],
                  re.compile("^jjux$"):["ꐨ"],
                  re.compile("^jjur$"):["ꐬ", "ꐫx"],
                  re.compile("^jjurx$"):["ꐫ"],
                  re.compile("^jjuo$"):["ꐡ", "ꐢp", "ꐠx"],
                  re.compile("^jjuop$"):["ꐢ"],
                  re.compile("^jjuox$"):["ꐠ"],
                 
                  
                  re.compile("^jjo$"):["ꐥ", "ꐦp", "ꐣt", "ꐤx"],
                  re.compile("^jjop$"):["ꐦ"],
                  re.compile("^jjot$"):["ꐣ"],
                  re.compile("^jjox$"):["ꐤ"],
                  
                  re.compile("^jjy$"):["ꐯ", "ꐰp", "ꐭt", "ꐮx"],
                  re.compile("^jjyp$"):["ꐰ"],
                  re.compile("^jjyt$"):["ꐭ"],
                  re.compile("^jjyx$"):["ꐮ"],
                  
                  re.compile("^nj$"):["ꐳi","ꐴip","ꐱit","ꐲix","ꐷie", "ꐸiep", "ꐵiet", "ꐶiex",
                            "ꑀu", "ꑁup", "ꐿux", "ꑃur", "ꑂurx", "ꏪuo", "ꐹuox",
                            "ꐽo", "ꐾop", "ꐻot", "ꐼox",
                            "ꑆy", "ꑇyp", "ꑄyt", "ꑅyx", "ꑉyr", "ꑈyrx"],
                            
                  re.compile("^nji$"):["ꐳ","ꐴp","ꐱt","ꐲx","ꐷe", "ꐸep", "ꐵet", "ꐶex"],                  
                  re.compile("^njip$"):["ꐴ"],
                  re.compile("^njit$"):["ꐱ"],
                  re.compile("^njix$"):["ꐲ"],                  
                  re.compile("^njie$"):["ꐷ", "ꐸp", "ꐵt", "ꐶx"],
                  re.compile("^njiep$"):["ꐸ"],
                  re.compile("^njiet$"):["ꐵ"],
                  re.compile("^njiex$"):["ꐶ"],

                  
                  re.compile("^nju$"):["ꑀ", "ꑁp", "ꐿx", "ꑃr", "ꑂrx", "ꏪo", "ꐹox"],
                  re.compile("^njup$"):["ꑁ"],
                  re.compile("^njux$"):["ꐿ"],
                  re.compile("^njur$"):["ꑃ", "ꑂx"],
                  re.compile("^njurx$"):["ꑂ"],
                  re.compile("^njuo$"):["ꐺ", "ꐹx"],
                  re.compile("^njuox$"):["ꐹ"],
                 
                  
                  re.compile("^njo$"):["ꐽ", "ꐾp", "ꐻt", "ꐼx"],
                  re.compile("^njop$"):["ꐾ"],
                  re.compile("^njot$"):["ꐻ"],
                  re.compile("^njox$"):["ꐼ"],
                  
                  re.compile("^njy$"):["ꑆ", "ꑇp", "ꑄt", "ꑅx", "ꑉr", "ꑈrx"],
                  re.compile("^njyp$"):["ꑇ"],
                  re.compile("^njyt$"):["ꑄ"],
                  re.compile("^njyx$"):["ꑅ"],
                  re.compile("^njyr$"):["ꑉ", "ꑈx"],
                  re.compile("^njyrx$"):["ꑈ"],
                  
                  re.compile("^ny$"):["ꑌi","ꑍip","ꑊit","ꑋix","ꑐie", "ꑑiep", "ꑎiet", "ꑏiex",
                            "ꑛu", "ꑜup", "ꑙut", "ꑚux", "ꑓuo", "ꑔuop", "ꑒuox",
                            "ꑗo", "ꑘop", "ꑕot", "ꑖox"],
                  re.compile("^nyi$"):["ꑌ","ꑍp","ꑊt","ꑋx","ꑐe", "ꑑep", "ꑎet", "ꑏex"],
                  re.compile("^nyip$"):["ꑍ"],
                  re.compile("^nyit$"):["ꑊ"],
                  re.compile("^nyix$"):["ꑋ"],                  
                  re.compile("^nyie$"):["ꑐ", "ꑑp", "ꑎt", "ꑏx"],
                  re.compile("^nyiep$"):["ꑑ"],
                  re.compile("^nyiet$"):["ꑎ"],
                  re.compile("^nyiex$"):["ꑏ"],

                  
                  re.compile("^nyu$"):["ꑛ", "ꑜp", "ꑙt", "ꑚx", "ꑓo", "ꑔop", "ꑒox"],
                  re.compile("^nyup$"):["ꑜ"],
                  re.compile("^nyut$"):["ꑙ"],
                  re.compile("^nyux$"):["ꑚ"],
                  re.compile("^nyuo$"):["ꑓ", "ꑔp", "ꑒx"],
                  re.compile("^nyuop$"):["ꑔ"],
                  re.compile("^nyuox$"):["ꑒ"],
                 
                  
                  re.compile("^nyo$"):["ꑗ", "ꑘp", "ꑕt", "ꑖx"],
                  re.compile("^nyop$"):["ꑘ"],
                  re.compile("^nyot$"):["ꑕ"],
                  re.compile("^nyox$"):["ꑖ"],
                  
                  re.compile("^x$"):["ꑟi","ꑠip","ꑝit","ꑞix","ꑣie","ꑤiep","ꑡiet","ꑢiex",
                            "ꑦuo", "ꑥuox",
                            "ꑩo", "ꑪop", "ꑧot", "ꑨox",
                            "ꑭy", "ꑮyp", "ꑫyt", "ꑬyx", "ꑰyr", "ꑯyrx"],
                  re.compile("^xi$"):["ꑟ","ꑠp","ꑝt","ꑞx","ꑣe", "ꑤep", "ꑡet", "ꑢex"],
                  re.compile("^xip$"):["ꑠ"],
                  re.compile("^xit$"):["ꑝ"],
                  re.compile("^xix$"):["ꑞ"],                  
                  re.compile("^xie$"):["ꑣ", "ꑤp", "ꑡt", "ꑢx"],
                  re.compile("^xiep$"):["ꑤ"],
                  re.compile("^xiet$"):["ꑡ"],
                  re.compile("^xiex$"):["ꑢ"],

                  
                  re.compile("^xu$"):["ꑦo", "ꑥox"],
                  re.compile("^xuo$"):["ꑦ", "ꑥx"],
                  re.compile("^xuox$"):["ꑥ"],
                 
                  
                  re.compile("^xo$"):["ꑩ", "ꑪp", "ꑧt", "ꑨx"],
                  re.compile("^xop$"):["ꑪ"],
                  re.compile("^xot$"):["ꑧ"],
                  re.compile("^xox$"):["ꑨ"],
                  
                  re.compile("^xy$"):["ꑭ", "ꑮp", "ꑫt", "ꑬx", "ꑰr", "ꑯrx"],
                  re.compile("^xyp$"):["ꑮ"],
                  re.compile("^xyt$"):["ꑫ"],
                  re.compile("^xyx$"):["ꑬ"],
                  re.compile("^xyr$"):["ꑰ", "ꑯx"],
                  re.compile("^xyrx$"):["ꑯ"],
                  
                  re.compile("^y$"):["ꑳi","ꑴip","ꑱit","ꑲix","ꑷie", "ꑸiep", "ꑵiet", "ꑶiex",
                            "ꒃu", "ꒄup", "ꒁut", "ꒂux", "ꒆur", "ꒅurx", "ꑻuo", "ꑼuop", "ꑹuot", "ꑺuox",
                            "ꑿo", "ꒀop", "ꑽot", "ꑾox",
                            "ꒉy", "ꒊyp", "ꒇyt", "ꒈyx", "ꒌyr", "ꒋyrx"],
                  re.compile("^yi$"):["ꑳ","ꑴp","ꑱt","ꑲx","ꑷe", "ꑸep", "ꑵet", "ꑶex"],
                  re.compile("^yip$"):["ꑴ"],
                  re.compile("^yit$"):["ꑱ"],
                  re.compile("^yix$"):["ꑲ"],                  
                  re.compile("^yie$"):["ꑷ", "ꑸp", "ꑵt", "ꑶx"],
                  re.compile("^yiep$"):["ꑸ"],
                  re.compile("^yiet$"):["ꑵ"],
                  re.compile("^yiex$"):["ꑶ"],

                  
                  re.compile("^yu$"):["ꒃ", "ꒄp", "ꒁt", "ꒂx", "ꒆr", "ꒅrx", "ꑻo", "ꑼop", "ꑹot", "ꑺox"],
                  re.compile("^yup$"):["ꒄ"],
                  re.compile("^yut$"):["ꒁ"],
                  re.compile("^yux$"):["ꒂ"],
                  re.compile("^yur$"):["ꒆ", "ꒅx"],
                  re.compile("^yurx$"):["ꒅ"],
                  re.compile("^yuo$"):["ꑻ"],
                  re.compile("^yuop$"):["ꑼ"],
                  re.compile("^yuot$"):["ꑹ"],
                  re.compile("^yuox$"):["ꑺ"],
                 
                  
                  re.compile("^yo$"):["ꑿ", "ꒀp", "ꑽt", "ꑾx"],
                  re.compile("^yop$"):["ꒀ"],
                  re.compile("^yot$"):["ꑽ"],
                  re.compile("^yox$"):["ꑾ"],
                  
                  re.compile("^yy$"):["ꒉ", "ꒊp", "ꒇt", "ꒈx", "ꒌr", "ꒋrx"],
                  re.compile("^yyp$"):["ꒊ"],
                  re.compile("^yyt$"):["ꒇ"],
                  re.compile("^yyx$"):["ꒈ"],
                  re.compile("^yyr$"):["ꒌ", "ꒋx"],
                  re.compile("^yyrx$"):["ꒋ"],
                  }
